### PR TITLE
Add map file for postal codes to community identification numbers

### PR DESCRIPTION
**Pull request by fsteeg**
Generated from http://www.fa-technik.adfc.de/code/opengeodb/DE.tab
```
awk -F "\t" '
NR < 2 { next }
{
	plz=$8
	ags=$2
	count=split(plz, plzs, ",")
	for(p in plzs)
	if(plzs[p] != "" && ags != "")
	printf ("%s\t%s\n", plzs[p], ags)
}' DE.tab | sort -u >> plz-ags-map.csv
```
See https://github.com/hbz/lobid-organisations/issues/134

### CODE REVIEW

**Comment by acka47** [comment]
It seems strange to me that some postal codes are mapped to multiple community IDs, e.g. 01454. Is this correct? Sometimes this seems to be the reason that nor key is set (see https://github.com/hbz/lobid-organisations/issues/134#issuecomment-245540384) because a postal code is mapped to multiple keys.

**Comment by acka47** [comment]
This seems right, looking at https://www.destatis.de/DE/ZahlenFakten/LaenderRegionen/Regionales/Gemeindeverzeichnis/Administrativ/Archiv/GVAuszugJ/31122014_Auszug_GV.xls?__blob=publicationFile (which might have been the better – because official – source for the mapping) there are two keys associated with 01454. We would have to add the nyme of the location to get the key...

**Comment by fsteeg** [comment]
Yes, I also found this: https://www.prospega.de/de/mediaratgeber/fachartikel/definitionen-ags-kgs-gemeinden-postleitzahlen ("Auf der anderen Seite kann eine Postleitzahl aber durchaus mehrere Gemeinden anschneiden.").

So, +1?

**Comment by acka47** [comment]
I guess adding the location name to the lookup table doesn't make sense.  So, +1 for now. But we should open another issue to address this problem in the future.

**Pull request merged**
