### PR TITLE
Update isil2opac_almaMmsId.tsv

### PR DESCRIPTION
**Pull request by eschackmann**
add DE-1871 and DE-1926

### CODE REVIEW

**Review by blackwinter — CHANGES_REQUESTED** [review]
OPAC links don't seem to work consistently.

DE-1871 (Hamm):

- [NZ](https://hbz-hhl.primo.exlibrisgroup.com/discovery/search?query=any,contains,990167204750206441&tab=LibraryCatalog&search_scope=MyInstitution&vid=49HBZ_HHL:VU1&offset=0) :x: (UPDATE: Location `VER` is suppressed) / [IZ](https://hbz-hhl.primo.exlibrisgroup.com/discovery/search?query=any,contains,991000158839706482&tab=LibraryCatalog&search_scope=MyInstitution&vid=49HBZ_HHL:VU1&offset=0) :heavy_check_mark:
- [NZ](https://hbz-hhl.primo.exlibrisgroup.com/discovery/search?query=any,contains,990219978790206441&tab=LibraryCatalog&search_scope=MyInstitution&vid=49HBZ_HHL:VU1&offset=0) :heavy_check_mark: (Available for)

DE-1926 (Lippstadt):

- [NZ](https://hbz-hhl.primo.exlibrisgroup.com/discovery/search?query=any,contains,990187205490206441&tab=LibraryCatalog&search_scope=MyInstitution&vid=49HBZ_HHL:VU1&offset=0) :x: (UPDATE: Location `Dep1_LP` is suppressed) / [IZ](https://hbz-hhl.primo.exlibrisgroup.com/discovery/search?query=any,contains,991001208631006482&tab=LibraryCatalog&search_scope=MyInstitution&vid=49HBZ_HHL:VU1&offset=0) :x: (UPDATE: No longer held by HHL)

**Comment by blackwinter** [comment]
Also: Uses spaces instead of tab as separator.

**Comment by TobiasNx** [comment]
Is this still relevant?

**Comment by eschackmann** [comment]
yepp

**Review by blackwinter — APPROVED** [review]

**Pull request merged**
