### PR TITLE
Add current mapping of almaMmsId to rpbId (RPB-50)

### PR DESCRIPTION
**Pull request by fsteeg**
To set the `rpbId` and `inCollection` during transformation in lobid-resources.

### CODE REVIEW

**Comment by TobiasNx** [comment]
+1 Does this file change over time? Do we need a cron job by @dr0i to update this file?

**Comment by TobiasNx** [comment]
Renamed the file as used in lobid

**Comment by fsteeg** [comment]
Will update this on Thursday, see https://github.com/hbz/lobid-resources/pull/1656#pullrequestreview-1338976998.

**Comment by fsteeg** [comment]
Updated almaMmsId2rpbId.tsv from test to initial prod data in https://github.com/hbz/lookup-tables/pull/12/commits/731e288b1b9149c2ae0ad54e46f1d2d474d00eb8.

**Review by TobiasNx — APPROVED** [review]

**Pull request merged**
