### PR TITLE
Add Alma sublibrary codes for FIZ (libraries without central cataloging).

### PR DESCRIPTION
**Pull request by blackwinter**
Required in lobid-resources for [DigiBib](https://github.com/hbz/lobid-resources/milestone/3).

### CODE REVIEW

**Review by dr0i — APPROVED** [review]

**Comment by blackwinter** [comment]
Thanks for the (quick) approval! Does this mean I can merge? (You can just assign me if that's the case.)

**Comment by dr0i** [comment]
> Does this mean I can merge? (You can just assign me if that's the case.)

I like the idea that the one who is assigned also do the merge.
So if you like you've could assigned me as reviewer only and let yourself assigned.
Sometimes I find it better to merge myself because it involves deployment (and for lobid-resources you don't know (yet) how to do this). Also here it's advisable to make something like https://github.com/hbz/lobid-resources/pull/1713 which you figured out yourself :)

**Comment by blackwinter** [comment]
> I like the idea that the one who is assigned also do the merge.

Exactly, that's why I would have expected you to assign me if that's what you wanted (which I didn't know).

> So if you like you've could assigned me as reviewer only and let yourself assigned.

Okay, I was under the impression that it should have been assigned to you first:

> At the end of the code review, the reviewer approves the pull request and **reassigns** the pull request to its original creator.

([Metafacture contributing guidelines](https://github.com/metafacture/metafacture-core/blob/master/CONTRIBUTING.md#code-review), emphasis mine)

**Comment by dr0i** [comment]
Yes, these are the guidelines for MF - they aren't applied to every repo of us - maybe that's a pity because it makes it complex of how to do things... I would like to argue that _if_ you program a library and no app has to be deployed after merging we do it like in the MF guidelines , and otherwise (apps!) we assign to someone who do the deployment.

**Pull request merged**
